theme: jekyll-theme-minimal
title: Robin's Portfolio
description: AI Medical Imaging & 3D Data Processing Specialist
show_downloads: false
github:
  is_project_page: false

# Enable custom CSS
include:
  - assets/css/style.css

# Custom variables
portfoliio:
  name: "Robin"
  tagline: "AI Medical Imaging & 3D Data Processing Specialist"